### ISSUE TITLE
Code needed to Mijia Contact Sensor

### ISSUE THREAD

**Issue by w35l3y** [orangebucket/Anidea-for-SmartThings#2]
https://github.com/orangebucket/Anidea-for-SmartThings/blob/c112a58498cb8c898ef5a5ee6987797368aa0ef6/devicetypes/orangebucket/anidea-for-aqara-contact.src/anidea-for-aqara-contact.groovy#L175

I had to add the following code before the line above to make it work with my `Mijia Contact Sensor`.
```
} else if (parsed.clusterId == 0x0006) {
	map = [ name: 'contact', value: parsed.data[-1] == 0x01?"open":"closed" ]
```

I searched for alternatives and yours seems the most simple. Thanks!

https://github.com/a4refillpad/Xiaomi/blob/master/devicetypes/a4refillpad/xiaomi-door-window-sensor.src/xiaomi-door-window-sensor.groovy
https://github.com/bspranger/Xiaomi/blob/master/devicetypes/bspranger/xiaomi-aqara-door-window-sensor.src/xiaomi-aqara-door-window-sensor.groovy
https://github.com/bspranger/Xiaomi/blob/master/devicetypes/bspranger/xiaomi-door-window-sensor.src/xiaomi-door-window-sensor.groovy

**Comment by orangebucket** [comment]
Closed to avoid accidental button presses.
