### ISSUE TITLE
Virtual Momentary still needs Button capability

### ISSUE THREAD

**Issue by steinauf85** [orangebucket/Anidea-for-SmartThings#28]
I understand why you created the virtual momentary DH to have a cleaner look than Button, but without the Button capabilities in Anidea for Virtual Momentary, it cannot be "pushed" in webCoRE. It would be most useful to have a single DH that combines all of these capabilities.

**Comment by orangebucket** [comment]
I'll have to ponder it. The Virtual Button already has a Momentary and pressing a button (real or virtual) is clearly what Momentary is made for.

I don't really like the idea of the Virtual Momentary in the ST environment. It just exists as a fudge really.

**Comment by orangebucket** [comment]
Closed issue as a precaution against pressing the wrong buttons.
