### ISSUE TITLE
Offline sensor temperature 

### ISSUE THREAD

**Issue by alefavara** [orangebucket/Anidea-for-SmartThings#53]
problems with continuous disconnections.  unfortunately the aqara temperature sensors often go offline and I don't understand why.  can you solve?  thank you so much

**Comment by humeka** [comment]
I moved my Smartthings hub close to the sensor and is appears a lot better. My WIFI is stronger than the Zigbee/Bluetooth signal from the sensor. Also changed the Device Handler to :
https://github.com/orangebucket/Anidea-for-SmartThings/blob/master/devicetypes/orangebucket/anidea-for-aqara-temperature.src/anidea-for-aqara-temperature.groovy
Which I think is a lot better :)
Hope this helps, but I'm a novice
